### ISSUE TITLE
ESM branch: Webpack > babel-loader error on develop and build commands

### ISSUE THREAD

**Issue by a-kriya** [a-kriya/gridsome#2]
## Description

A sample project exists in [`gridsome/lib/__tests__/__fixtures__/project-simple`](https://github.com/a-kriya/gridsome/tree/master/gridsome/lib/__tests__/__fixtures__) which is used as part of e2e test [project-simple.build.e2e.js](https://github.com/a-kriya/gridsome/blob/master/gridsome/lib/__tests__/project-simple.build.e2e.js) for verifying the build command. With the migration to ESM, the build command and the test currently fails due to a TypeError in the compilation process.

### Steps to reproduce

- `git checkout esm`
- `cd gridsome/lib/__tests__/__fixtures__/project-simple`
- `npm run build`

### Expected result

A successful build, generating and outputting a single index.html file to `dist` directory in `project-simple`, and a passing `project-simple.build.e2e.js` test.

### Actual result

```
> test-project-simple@1.0.0 develop
> gridsome develop

Gridsome v0.9.1

Initializing plugins...
Load sources - 0s
Create GraphQL schema - 0.02s
Create pages and templates - 0.01s
Generate temporary code - 0.01s
Bootstrap finish - 0.12s
10% building 0/4 entries 4/4 dependencies 0/4 modulesnode:internal/modules/esm/utils:213
  throw new ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING();
        ^

TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:213:9)
    at Object.<anonymous> (gridsome/node_modules/babel-loader/lib/cache.js:22:23)
    at Object.<anonymous> (gridsome/node_modules/@httptoolkit/esm/esm.js:1:278385)
    at require.Module._extensions (gridsome/node_modules/@httptoolkit/esm/esm.js:1:61)
    at Object._p (gridsome/node_modules/@httptoolkit/esm/esm.js:1:313366)
    at p (gridsome/node_modules/@httptoolkit/esm/esm.js:1:314668)
    at ol (gridsome/node_modules/@httptoolkit/esm/esm.js:1:274743)
    at Object.u (gridsome/node_modules/@httptoolkit/esm/esm.js:1:314916)
    at Object.o (gridsome/node_modules/@httptoolkit/esm/esm.js:1:314316)
    at Object.<anonymous> (gridsome/node_modules/@httptoolkit/esm/esm.js:1:312073) {
  code: 'ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING'
}

Node.js v20.11.0
```

### Environment

    Node: 20.11.0 - /opt/homebrew/opt/node@20/bin/node
    npm: 10.2.4 - /opt/homebrew/opt/node@20/bin/npm

**Comment by milindsingh** [comment]
@a-kriya Can you share your contact details? Maybe we can connect and revive this project!
I have been searching a similar framework but didn't find one. Also Gatsby is also unmaintained, so didn't any alternative at the moment.

**Comment by a-kriya** [comment]
@milindsingh Yes, Gridsome was quite something. I tried Nuxt, Astro, Sveltekit and they all seemed convoluted or did not provide the sane behavior that I had come to expect after using Gridsome.

Migrating Gridsome to Vite/Vue 3 is a big undertaking and I do not have the resources for it. I only forked it to keep things on life-support until I found something to switch to, and I recently did: [ViteSSG](https://www.npmjs.com/package/vite-ssg). It is one piece of the puzzle and is crudely documented, but along with a few other packages, it gave me everything I needed to migrate my packages to Vite/Vue 3/TS.

A working sample of ViteSSG can be seen at https://github.com/antfu/antfu.me.
